#!/usr/bin/env bash
#
# STAGE 2 of the simulation programme: does an ENGINEERED image-to-trial allocation recover the
# perceptual space better than the random allocation the task currently deploys?
#
# The deployed task allocates independently per subject - shuffle the 725 images, take the first
# 360, chop into 18 trials of 20 (SpAM_Task/js/trial_generator.js:56). Nothing coordinates across
# subjects, so which image pairs get judged is left entirely to chance and the pair coverage follows
# 1 - exp(-0.01303*N): about 32% at N=30, 98% at N=300. The alternative is a balanced covering in the
# spirit of MacDonald (2020, 10.3758/s13428-019-01326-x), generated by block_design.greedy_session_design,
# which additionally keeps each subject's trials image-disjoint so a session stays deployable.
#
# TWO SUB-STAGES.
#   2a  DESIGN ONLY (out/design_only.csv). Pure combinatorics: no subjects, no MDS, no R. Cheap,
#       deterministic, and it isolates the allocation effect from every downstream modelling choice.
#       If the arms do not separate here there is nothing for 2b to find, so it runs and is pushed
#       FIRST. It also prices the per-session disjointness constraint via a third, non-deployable
#       `designed_unconstrained` arm.
#   2b  FULL SIMULATION. Both arms as ONE sweep, with `allocation_mode` (0.0 random / 1.0 designed)
#       as a swept numeric lever inside TaskV4SimulationConfig. That puts both arms in a single
#       ResultStore keyed on the same ground truth and noise draw, and every compute_* table gains
#       an `allocation_mode` grouping column for free.
#
# WHY ONE STORE AND NOT ONE PER ARM (deviation from the plan, recorded deliberately). Running the
# arms as separate sweeps would mean two stores, two sets of group keys and a manual join, and
# nothing would structurally guarantee the two arms shared a ground truth. As a lever the arm rides
# inside the parameters, survives the ResultStore round-trip (pipeline._task_key coerces each field
# with float(), which is why the mode is numeric), and is recovered from meta.csv on resume.
#
# A FRESH DESIGN PER REP, not one design shared across reps. A shared design would give the designed
# arm zero allocation variance while the random arm carries it, so the two arms' spreads would not be
# comparable and the whole result would rest on the quality of a single greedy draw. Cost is
# negligible: about 1.7 s per design, ~40 designs.
#
# SCREENED-OUT CANDIDATES DO NOT BURN A DESIGN SLOT. DesignedAllocator.draw is paired with
# commit/rollback, so a candidate who fails screening returns their session to the pool. The design is
# a plan over the subjects who end up ANALYSED; consuming a slot per candidate would degrade the
# designed arm's coverage in proportion to the rejection rate and confound the arm comparison with
# the screening threshold.
#
# THE GROUND TRUTH IS PULLED, NEVER REBUILT. Stage 1 (run_gt_construction.sh) produced gt/selection.json
# and the coordinates; this script fails fast if they are absent. Rebuilding here would silently
# change the ground truth between runs and make the arms incomparable across invocations.
#
# NOISE IS CALIBRATED ON ALL 47 PILOT SUBJECTS (pre AND post SHINE), unlike the ground truth, which is
# pre-SHINE only. The reason is that the noise fit estimates a property of SUBJECTS - how reliably a
# person repeats their own arrangement - not a property of the images, so the post-SHINE half is
# perfectly good evidence about it, whereas it is unusable for a GT over the pre-SHINE stimulus set.
#
# WHERE THE CONTRAST IS INFORMATIVE. It is squeezed at both ends: at N=300 random already covers 98%
# of pairs so there is almost nothing left to win, and at N=30 both arms may be too sparse to recover
# anything. The informative window is N=50-75. Report N=300 as a "no cost at scale" check, not as a
# null result.
#
# CONFDISTS ARE NOT UPLOADED. upload_and_finish excludes confdists.f32: it is exactly pdist(conf) per
# row and therefore fully recoverable from confs.f32, which is ~20x smaller. store_conf=True is
# ASSERTED below rather than inherited, because the local cluster analysis is dead without confs.f32.
#
# Prerequisites (see Cookbook.md)
#   * Stage 1 has completed and its gt/ prefix is staged at $GT_S3_URI (defaults to $S3_URI).
#   * The FLAT data dir staged under $S3_URI/data (PRIVATE - human-subjects data).
#
# Usage:
#   export REPO_URL=https://github.com/<you>/hierarchical_image_database.git
#   export GIT_REF=main
#   export S3_URI=s3://<your-bucket>/spam-simulations/design-comparison   # FRESH prefix; PRIVATE
#   export GT_S3_URI=s3://<your-bucket>/spam-simulations/gt-construction  # where stage 1 wrote gt/
#   # export REPS=10        # cohorts per cell -> C(10,2)=45 cohort pairs. MUST be >= 10.
#   # export NDIMS=...      # override the D grid derived from gt/selection.json
#   bash run_design_comparison.sh
#
# Grid: 4 num_subjects x 2 arms x ~6 ndims x 10 reps = ~480 MDS fits (itmax=1000, precalc_init=True).
# At the ~3.2 s/fit measured on a c7i.4xlarge that is roughly 30 min of SMACOF plus generation, which
# for the screened arms is slower than it looks because rejected candidates are simulated and thrown
# away. REMEMBER TO TERMINATE THE INSTANCE WHEN DONE.

set -euo pipefail

# --------------------------------------------------------------------------- configuration
REPO_URL="${REPO_URL:?set REPO_URL to your repo (https with PAT, or git@ ssh)}"
GIT_REF="${GIT_REF:-main}"
S3_URI="${S3_URI:?set S3_URI, e.g. s3://my-bucket/spam-simulations/design-comparison}"
GT_S3_URI="${GT_S3_URI:-$S3_URI}"         # where run_gt_construction.sh wrote gt/
WORKDIR="${WORKDIR:-$HOME/spam_run}"
GT_METHOD="${GT_METHOD:-smacof}"
# C(6,2)=15 cohort pairs gives visibly wide SEMs on every between-cohort curve, and the cluster
# metrics in particular are read off those SEMs by the one-SE rule. C(10,2)=45 is the design point.
REPS="${REPS:-10}"
if [ "$REPS" -lt 10 ]; then
  echo "!! REPS=$REPS gives only $(( REPS * (REPS - 1) / 2 )) cohort pairs. The between-cohort SEMs"
  echo "!! are what the k-selection rule reads; use REPS>=10 (45 pairs) or override deliberately."
  exit 1
fi
N_JOBS="${N_JOBS:-$(( $(nproc) * 2 / 3 ))}"
export R_LIBS_USER="${R_LIBS_USER:-$HOME/R/library}"

# --------------------------------------------------------------------------- logging
LOGFILE="${WORKDIR%/}.log"
: > "$LOGFILE"
exec > >(tee -a "$LOGFILE") 2>&1
_START_TS=$(date -u +%s)
echo ">> [start] $(date -u +'%Y-%m-%dT%H:%M:%SZ')  (S3_URI=$S3_URI, designed vs random)"

_on_exit() {
  local rc=$?
  [ -n "${PILOT_DIR:-}" ] && rm -rf "$PILOT_DIR"   # human-subjects data never left on the box
  echo ">> [end] $(date -u +'%Y-%m-%dT%H:%M:%SZ')  (exit $rc, elapsed $(( $(date -u +%s) - _START_TS ))s)"
  if [ -n "${S3_URI:-}" ]; then
    sleep 1   # let the tee subprocess flush the final lines before we upload
    aws s3 cp "$LOGFILE" "$S3_URI/run_design_comparison.log" --only-show-errors || true
  fi
}
trap _on_exit EXIT

# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/prepare_machine.sh"

# --------------------------------------------------------------------------- pilot loader
git sparse-checkout add analysis/utils || true
if [ ! -f analysis/utils/parser.py ]; then
  echo ">> [calibrate] sparse add didn't materialise analysis/utils; forcing a path checkout ..."
  git checkout "$GIT_REF" -- analysis/utils 2>/dev/null \
    || git checkout HEAD -- analysis/utils 2>/dev/null || true
fi
if [ ! -f analysis/utils/parser.py ]; then
  echo "!! [calibrate] analysis/utils/parser.py still missing (checked out ref: $GIT_REF)."
  echo "!! sparse-checkout list:"; git sparse-checkout list || true
  exit 1
fi
echo ">> [calibrate] pilot parser present: analysis/utils/parser.py"

PILOT_DIR="data"
echo ">> [calibrate] fetching participant data from $S3_URI/data ..."
mkdir -p "$PILOT_DIR"
aws s3 sync "$S3_URI/data" "$PILOT_DIR/" --only-show-errors
shopt -s nullglob; _csvs=("$PILOT_DIR"/*.csv); shopt -u nullglob
if [ ${#_csvs[@]} -eq 0 ] || [ ! -f "$PILOT_DIR/stimuli_manifest.json" ]; then
  echo "!! [calibrate] no *.csv and/or stimuli_manifest.json under $S3_URI/data"
  exit 1
fi

# --------------------------------------------------------------------------- stage 1 artifacts
# Pulled from GT_S3_URI, which may differ from this run's prefix - the ground truth is shared across
# stage-2 runs by design, so it lives wherever stage 1 put it.
echo ">> [gt] pulling stage-1 ground truth from $GT_S3_URI/gt/ ..."
mkdir -p gt
aws s3 sync "$GT_S3_URI/gt/" gt/ --only-show-errors || true
if [ ! -f gt/selection.json ]; then
  echo "!! [gt] gt/selection.json not found under $GT_S3_URI/gt/."
  echo "!! Stage 2 never rebuilds the ground truth - rebuilding it here would silently change it"
  echo "!! between arms and between runs. Run run_gt_construction.sh first."
  exit 1
fi
echo ">> [gt] selection:"; cat gt/selection.json

# Resume: run_mds_sweep skips tasks already recorded in the store (pipeline.py:298-308).
stage_pull mds_store
stage_pull out

# --------------------------------------------------------------------------- the sweep
N_JOBS="$N_JOBS" GT_METHOD="$GT_METHOD" REPS="$REPS" S3_URI="$S3_URI" \
  NDIMS="${NDIMS:-}" N_LIST="${N_LIST:-30,50,75,300}" SEED="${SEED:-42}" \
  MINREL="${MINREL:-0.0}" DESIGN_REPS_2A="${DESIGN_REPS_2A:-20}" \
  python - <<'PY'
import json
import os
import pathlib
import subprocess

import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist

from SpAM_Simulations import design_comparison, pipeline, validity
from SpAM_Simulations.allocation import DESIGNED, RANDOM, make_allocator
from SpAM_Simulations.block_design import greedy_session_design
from SpAM_Simulations.config import MDSSweepConfig, TaskV4SimulationConfig
from SpAM_Simulations.gt_construction import aggregate_subjects
from SpAM_Simulations.pilot import (
    between_subject_agreement, fit_dispersion_for_agreement, fit_noise_for_test_retest,
    fit_noise_population, load_pilot_subjects, subject_reliability_sample,
)

OUT = pathlib.Path("out"); OUT.mkdir(exist_ok=True)
CAL = pathlib.Path("calibration"); CAL.mkdir(exist_ok=True)
PILOT, MANIFEST = "data", "data/stimuli_manifest.json"
N_JOBS = int(os.environ["N_JOBS"])
REPS, SEED = int(os.environ["REPS"]), int(os.environ["SEED"])
FULL_N = [int(x) for x in os.environ["N_LIST"].split(",")]
MINREL = float(os.environ["MINREL"])


def push(prefix: str, msg: str) -> None:
    """Publish one local directory. Non-fatal: a transient S3 error must not discard local work."""
    print(f"[push] {msg}", flush=True)
    rc = subprocess.run(["aws", "s3", "sync", f"{prefix}/", f"{os.environ['S3_URI']}/{prefix}/",
                         "--only-show-errors", "--exclude", "*confdists.f32"],
                        check=False).returncode
    if rc != 0:
        print(f"[push] WARNING: sync exited {rc}; results are still on local disk", flush=True)


# --- the deployed design (SpAM_Task/task_config.json v4.0), fixed rather than swept -----------
IMAGES_PER_TRIAL = 20
SCREEN_TRIALS, SCREEN_REPEATS = 8, 2       # screening block: 6 distinct + 2 repeats
EXP_TRIALS, EXP_REPEATS = 14, 2            # experimental block: 12 distinct + 2 repeats
SCREEN_DISTINCT = SCREEN_TRIALS - SCREEN_REPEATS          # 6
MAIN_DISTINCT = EXP_TRIALS - EXP_REPEATS                  # 12
TRIALS_PER_SESSION = SCREEN_DISTINCT + MAIN_DISTINCT      # 18 distinct trials -> 360 images
FRAC_REPEATED = EXP_REPEATS / EXP_TRIALS

# --- stage 1 artifacts ------------------------------------------------------------------------
selection = json.loads(pathlib.Path("gt/selection.json").read_text())
D_GT = int(selection["n_dims"])
coords = np.load(pathlib.Path("gt") / selection["gt_file"])
N_IMAGES = int(coords.shape[0])
print(f"[gt] n_dims={D_GT}, coords {coords.shape} from {selection['gt_file']}", flush=True)

# The D grid must span below, at and above the selected D_gt: fitting only at D_gt would beg the
# question, since a sweep that recovers structure only at exactly the dimensionality it was
# generated in has demonstrated nothing about the real data. Capped at 20, and max(D) is what sets
# the download size (conf rows are zero-padded to max_ndim).
if os.environ.get("NDIMS"):
    NDIMS = sorted({int(x) for x in os.environ["NDIMS"].split(",")})
else:
    NDIMS = sorted({min(20, max(2, D_GT + off)) for off in (-3, -1, 0, 2, 5, 10)})
print(f"[grid] ndims={NDIMS} (D_gt={D_GT}), num_subjects={FULL_N}, reps={REPS}, "
      f"arms=[random, designed] -> {len(NDIMS) * len(FULL_N) * REPS * 2} MDS fits", flush=True)

# --- stage 2a: the design alone ---------------------------------------------------------------
# Pure combinatorics, ~1 min, and it runs first so its answer is banked before any SMACOF starts.
if not (OUT / "design_only.csv").exists():
    d2a = design_comparison.compare_designs(
        n_images=N_IMAGES, k=IMAGES_PER_TRIAL, trials_per_session=TRIALS_PER_SESSION,
        n_list=FULL_N, reps=int(os.environ["DESIGN_REPS_2A"]), seed=SEED)
    d2a.to_csv(OUT / "design_only.csv", index=False)
    print("\n[2a] design-only comparison:\n"
          + design_comparison.summarise_comparison(d2a).to_string(index=False), flush=True)
    push("out", "stage 2a")
else:
    print("[2a] out/design_only.csv already present, skipping", flush=True)

# --- calibration ------------------------------------------------------------------------------
# On ALL pilot subjects (both SHINE variants): reliability and between-subject agreement are
# properties of people, not of the stimulus set.
allsub = load_pilot_subjects(PILOT, MANIFEST)
print(f"\n[calibrate] {len(allsub)} pilot sessions (both SHINE variants) for the noise fit",
      flush=True)

emp = subject_reliability_sample(allsub)
print(f"[shape] empirical reliability: n={len(emp)} median={np.median(emp):.3f} "
      f"q10={np.quantile(emp, .1):.3f} q90={np.quantile(emp, .9):.3f}", flush=True)
fit = fit_noise_population(coords, emp, images_per_trial=IMAGES_PER_TRIAL,
                           perspective_dispersion=0.2, n_subjects=80, reps=3, verbose=True)
FB = fit["best"]
fit["grid"].to_csv(CAL / "noise_shape_grid.csv", index=False)
(CAL / "noise_shape_fit.json").write_text(json.dumps(
    {k: (float(v) if isinstance(v, (int, float, np.floating)) else v) for k, v in FB.items()},
    indent=2, default=str))
print(f"[shape] best: family={FB['family']} shape={FB['shape']} scale={FB['noise_scale']} "
      f"W1={FB['distance']:.4f} CV={FB['cv']:.3f} boundary={FB['at_shape_boundary']}", flush=True)
if FB["at_shape_boundary"]:
    print("[shape] WARNING: fit sits on a shape-grid boundary - the family, not the data, is the "
          "binding constraint.")
LOGN_SIGMA = float(FB["shape"]) if FB["family"] == "lognormal" else 0.0
SHAPE_DF = int(FB["shape"]) if FB["family"] == "t" else 5

# Dispersion is re-fitted UNDER the newly fitted noise population: agreement depends on the whole
# noise distribution, so a dispersion calibrated against a different one does not transfer.
emp_agr = between_subject_agreement(np.vstack([s.distances for s in allsub]),
                                    min_overlap=20)["mean_agreement"]
DISP, disp_ach = fit_dispersion_for_agreement(
    coords, emp_agr, noise_scale=float(FB["noise_scale"]), noise_df=SHAPE_DF,
    lognormal_sigma=LOGN_SIGMA, images_per_trial=IMAGES_PER_TRIAL, reps=REPS)
print(f"[disp] empirical agreement={emp_agr:.4f} -> dispersion={DISP:.2f} (achieved {disp_ach:.4f})",
      flush=True)

# One noise level, at the empirically achieved test-retest. The R axis was swept in task-v4-fitted
# and is not what THIS run is about: holding it fixed keeps every fit paying for the arm contrast.
TARGET_R = float(np.median(emp))
NOISE, ach_r = fit_noise_for_test_retest(coords, TARGET_R, noise_df=SHAPE_DF,
                                         lognormal_sigma=LOGN_SIGMA,
                                         images_per_trial=IMAGES_PER_TRIAL, reps=REPS)
print(f"[invert] targetR={TARGET_R:.3f} -> noise={NOISE:.2f} (achieved {ach_r:.3f} @img20)",
      flush=True)
(CAL / "calibration.json").write_text(json.dumps(dict(
    n_pilot_sessions=len(allsub), empirical_agreement=float(emp_agr), dispersion=float(DISP),
    dispersion_achieved=float(disp_ach), target_test_retest=TARGET_R,
    achieved_tr_unscreened=float(ach_r), subjects_noise_scale=float(NOISE),
    noise_family=FB["family"], noise_shape=float(FB["shape"]), n_dims=D_GT,
), indent=2))
push("calibration", "calibration artifacts")

# --- stage 2b: the allocator factory ----------------------------------------------------------
# One design per (num_subjects, rep), generated on first use and cached so that cells differing only
# in ndim share it (they must: ndim is an MDS choice made after the data exist). A FRESH design per
# rep is the point - see the header.
_designs = {}


def allocator_factory(params, rep):
    """Build the allocation for one scheduled cell, or None to keep the inline random path.

    Returning None for the random arm is deliberate rather than lazy: it leaves that arm
    bit-for-bit identical to every previously published run (test_bit_exact_v4.py), so the
    comparison is against the real baseline and not against a re-implementation of it.
    """
    if float(params.allocation_mode) != DESIGNED:
        return None
    n = int(params.num_subjects)
    key = (n, rep)
    if key not in _designs:
        rng = np.random.default_rng([SEED, 7, n, rep])
        # Only RETAINED subjects consume a session (rollback returns a screened-out candidate's),
        # so n sessions suffice; the small margin absorbs any off-by-one at the boundary.
        _designs[key] = greedy_session_design(N_IMAGES, IMAGES_PER_TRIAL, TRIALS_PER_SESSION,
                                              n + 5, rng)
        print(f"[design] built a fresh session design for N={n}, rep={rep}", flush=True)
    return make_allocator(DESIGNED, n_images=N_IMAGES, k=IMAGES_PER_TRIAL,
                          screen_distinct=SCREEN_DISTINCT, main_distinct=MAIN_DISTINCT,
                          sessions=_designs[key])


cfg = TaskV4SimulationConfig(
    gt_embeddings=coords, num_subjects=FULL_N,
    trials_per_subject=[EXP_TRIALS], images_per_trial=[IMAGES_PER_TRIAL],
    subjects_noise_scale=[NOISE], subjects_noise_df=[SHAPE_DF],
    subjects_noise_lognormal_sigma=[LOGN_SIGMA],
    frac_trials_repeated=[FRAC_REPEATED], perspective_dispersion=[round(DISP, 2)],
    screening_trials=[SCREEN_TRIALS], screening_repeats=[SCREEN_REPEATS],
    screening_min_reliability=[MINREL],
    allocation_mode=[RANDOM, DESIGNED],
    reps=REPS, seed=SEED,
)
sim = pipeline.generate_task_v4_simulation(cfg, verbose=True, allocator_factory=allocator_factory)

sweep = MDSSweepConfig(ndims=NDIMS, max_iters=1000, convergence_tol=1e-6, precalc_init=True)
# store_conf ASSERTED, not inherited: the local cluster analysis reads confs.f32 and nothing else,
# and a store written without it cannot be repaired after the instance is gone.
store = pipeline.run_mds_sweep(sim, sweep, "mds_store", parallel=True, n_jobs=N_JOBS,
                               store_conf=True, verbose=True)
if not store.stores_conf:
    raise SystemExit("the store holds no configurations; the cluster analysis needs confs.f32")
print(f"\n[sweep] {len(store)} MDS results", flush=True)

# --- metric tables ----------------------------------------------------------------------------
# group_fields=None groups by every swept parameter x ndim, with `rep` as the within-group axis,
# so `allocation_mode` becomes a column of each table without any extra plumbing.
pipeline.compute_coverage_table(sim).to_csv(OUT / "coverage.csv", index=False)
pipeline.compute_stability_table(sim).to_csv(OUT / "stability.csv", index=False)
pipeline.compute_embedding_stability(store).to_csv(OUT / "embedding_stability.csv", index=False)
pipeline.compute_embedding_generalizability(store).to_csv(
    OUT / "embedding_generalizability.csv", index=False)
pipeline.compute_topk_similar_pair_stability(store).to_csv(OUT / "topk_jaccard.csv", index=False)
pipeline.compute_recovery_vs_gt(store, pdist(coords)).to_csv(OUT / "recovery_vs_gt.csv", index=False)
push("out", "metric tables")

# --- validity: are the simulated cohorts structurally realistic? -------------------------------
# The floor check. If the semantic gradient (same-subcategory < same-category < cross-category)
# does not reproduce, the simulated cohorts are not realistic and the ARM COMPARISON SHOULD NOT BE
# TRUSTED, regardless of how clean the arm contrast looks.
manifest_images = json.loads(pathlib.Path(MANIFEST).read_text())["images"]
if len(manifest_images) != N_IMAGES:
    raise SystemExit(f"manifest has {len(manifest_images)} images but the GT has {N_IMAGES}; "
                     f"the hierarchy levels would be misaligned with the distance vector")
pilot_mean, pilot_w = aggregate_subjects(allsub)
pilot_condensed = np.where(pilot_w > 0, pilot_mean, np.nan)

reports, grads = {}, []
for arm, mode in (("random", RANDOM), ("designed", DESIGNED)):
    cells = [(p, res) for p, res in sim._results.items()
             if float(p.allocation_mode) == mode and int(p.num_subjects) == max(FULL_N)]
    if not cells:
        continue
    _params, results = cells[0]
    sim_mean, sim_w = pipeline._prepare_mds_inputs(results[0])
    sim_condensed = np.where(sim_w > 0, sim_mean, np.nan)
    rep = validity.compare_to_pilot(sim_condensed, pilot_condensed, manifest_images)
    grads.append(rep["gradient"].assign(arm=arm))
    reports[arm] = {k: v for k, v in rep.items() if k != "gradient"}
    print(f"\n[validity/{arm}] N={max(FULL_N)} monotone_sim={rep['sim_gradient_monotone']} "
          f"monotone_pilot={rep['pilot_gradient_monotone']} "
          f"max|std_gap_diff|={rep['max_abs_std_gap_diff']:.3f}", flush=True)
    print(rep["gradient"].to_string(index=False), flush=True)
    if not rep["sim_gradient_monotone"]:
        print(f"[validity/{arm}] WARNING: the simulated semantic gradient is NOT monotone. The "
              f"cohorts are not structurally realistic; do not trust the arm comparison.",
              flush=True)

if grads:
    pd.concat(grads, ignore_index=True).to_csv(OUT / "validity_gradient.csv", index=False)

# --- validity: does the NOISE have the right shape, not just the signal? ----------------------
# Empirically, RMSE between a pair's two judgements is an inverted U against their mean distance:
# clearly-similar and clearly-dissimilar pairs are judged consistently, the ambiguous middle is not.
# This is a property of the noise model rather than of any sweep cell, so it is measured directly
# from the calibrated generative model - no MDS, seconds to run.
sim_pairs = validity.simulate_repeat_pairs(
    coords, subjects_noise_scale=NOISE, n_subjects=60, trials_per_subject=4,
    images_per_trial=IMAGES_PER_TRIAL, perspective_dispersion=float(DISP),
    noise_df=SHAPE_DF, lognormal_sigma=LOGN_SIGMA, seed=SEED)
pilot_repeat = validity.repeat_pairs(allsub)
if pilot_repeat[0].size:
    noise_cmp = validity.compare_noise_vs_distance(sim_pairs, pilot_repeat)
    noise_cmp["curves"].to_csv(OUT / "noise_vs_distance.csv", index=False)
    noise_cmp["shape"].to_csv(OUT / "noise_curve_shape.csv", index=False)
    print("\n[validity/noise] RMSE vs distance, both sources:", flush=True)
    print(noise_cmp["shape"].to_string(index=False), flush=True)
    # The low flank is near-forced (distances cannot go below zero) so agreeing there says little.
    # The high flank is the discriminating one, and the model is EXPECTED to miss it: it places
    # points on an unbounded plane, while real subjects work on a bounded canvas.
    if not noise_cmp["turnover_matches"]:
        print(f"[validity/noise] the curve does not turn over as the pilot's does "
              f"(drop_gap={noise_cmp['drop_gap']:.3f}). Check the canvas bound is active.",
              flush=True)
    if not noise_cmp["low_end_matches"]:
        print("[validity/noise] WARNING: the LOW end does not match either. That one is "
              "near-forced for any additive-noise model, so a mismatch there points at a real "
              "problem with the noise model.", flush=True)
else:
    print("\n[validity/noise] no pilot repeat trials found; skipping the noise-shape check",
          flush=True)

(OUT / "validity.json").write_text(json.dumps(reports, indent=2, default=str))
print("\n[done] stage 2 complete", flush=True)
PY

upload_and_finish
